### PR TITLE
#FN-24 feat: Implement Wishlist

### PR DESCRIPTION
**Pull request by EvelyneUmubyeyi**
# PR Description

In this PR, I worked on wishlist management for buyer, where they can add a product they want to the wishlist, view a list of products in their wishlist, remove an item from their wishlist, and clear their wishlist.  
## Description of tasks that were expected to be completed

List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style

- [x] Create products page where buyers can add a product to their wishlist
- [x] Create wishlist page where buyers can view and edit their wishlist

## Description of tasks that were expected to be completed and that are not yet completed

- [ ] None

## How this may be tested?

Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

1. run `yarn i` to install all required dependencies
2. run `yarn run dev`
3. Go to products page /products and wishlist page /wishlist

## Screenshots (If appropriate/applicable)

Provide screenshots related to your PR in case it's appropriate and applicable

## Please check this Checklist before you submit your PR:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

### CODE REVIEW

**Review by Niyobuzima — COMMENTED** [review]
Great work, kindly add a navigation so that a user can go to products without using the url and also the products are viewed depending on the category they are; you can't see them mixed work on that

**Review by Niyobuzima — APPROVED** [review]
LGTM

**Review by nellykawera — APPROVED** [review]
Aproved this PR

**Review by dushimeemma — CHANGES_REQUESTED** [review]
- where can I click to navigate to /products?
- where can I click to navigate to /wishlist?

**Review by Illustre13 — APPROVED** [review]

**Review by dushimeemma — APPROVED** [review]

**Pull request merged**
