### PR TITLE
#FN-51 chore: Configure storybook for component development

### PR DESCRIPTION
**Pull request by EvelyneUmubyeyi**
# Trello card
https://trello.com/c/rudNMOfe

# PR Description
I configured storybook in the project and created sample stories of a button.
## Description of tasks that were expected to be completed
List all the tasks and sub-tasks that were assigned to you Make sure you check every completed task. list them in this style
- [x] Configured storybook in the project
- [x] Added sample stories to the project
## Description of tasks that were expected to be completed and that are not yet completed
- [x] None
## How this may be tested?
Please describe the tests that you ran to verify your functionalities. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.
1. run `npm i` to install all required dependencies
2. run `npm run storybook`
## Screenshots (If appropriate/applicable)
Provide screenshots related to your PR in case it's appropriate and applicable
## Please check this Checklist before you submit your PR:
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] My code generates no warnings
- [x] There are no vulnerabilities

### CODE REVIEW

**Review by Niyobuzima — APPROVED** [review]
LGTM!

**Review by kunda4 — APPROVED** [review]
Well done

**Review by Illustre13 — APPROVED** [review]
Well Done, just rebase to  resolve conflicts

**Review by dushimeemma — APPROVED** [review]
Good job 🥇

**Pull request merged**
